<a href="https://colab.research.google.com/github/suemnjeri/Deep-learning---vision-cnn-nlp/blob/main/COMPUTER_VISION_MNIST_%26_FASHION_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# FASHION MNIST

In [1]:
import tensorflow as tf

fashion_mnist = tf.keras.datasets.fashion_mnist

(x_train_fashion, y_train_fashion), (x_test_fashion, y_test_fashion) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [2]:
x_train_fashion.shape

(60000, 28, 28)

In [3]:
x_test_fashion.shape

(10000, 28, 28)

In [4]:
y_test_fashion.shape

(10000,)

In [5]:
y_test_fashion[0]

9

In [6]:
import numpy as np
np.set_printoptions(linewidth=200)

In [7]:
len(np.unique(y_test_fashion))

10

In [8]:
print(x_train_fashion[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0  13  73   0   0   1   4   0   0   0   0   1   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3   0  36 136 127  62  54   0   0   0   1   3   4   0   0   3]
 [  0   0   0   0   0   0   0   0   0   0   0   0   6   0 102 204 176 134 144 123  23   0   0   0   0  12  10   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0 155 236 207 178 107 156 161 109  64  23  77 130  72  15]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0  69 207 223 218 216 216 163 127 121 122 146 141  88 172  66]
 [  0   0   0   0   0   0   0   0   0   1   1   1   0 200 232 232 233 229 223 22

In [9]:
print(x_train_fashion[59999])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   1  71  13   4   0   

In [10]:
print(y_train_fashion[59999])

5


0 	T-shirt/top
1 	Trouser
2 	Pullover
3 	Dress
4 	Coat
5 	Sandal
6 	Shirt
7 	Sneaker
8 	Bag
9 	Ankle boot

In [11]:
x_train_fashion = x_train_fashion / 255.0
x_test_fashion = x_test_fashion / 255.0

In [12]:
model_fashion = tf.keras.models.Sequential([
                   tf.keras.layers.Flatten(),
                   tf.keras.layers.Dense(512, activation = 'relu'),
                   tf.keras.layers.Dense(10, activation='softmax')             
])

In [13]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epochs, logs={}):
    if(logs.get('accuracy')>=0.99):
      print('Reached 99% accuracy so cancelling training!')
      self.model.stop_training = True

callbacks = myCallback()

In [14]:
model_fashion.compile(optimizer = 'adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [15]:
model_fashion.fit(x_train_fashion, y_train_fashion, epochs=20, callbacks=[callbacks])

Epoch 1/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.5883 - accuracy: 0.7950
Epoch 2/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3701 - accuracy: 0.8655
Epoch 3/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3270 - accuracy: 0.8808
Epoch 4/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2990 - accuracy: 0.8901
Epoch 5/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2757 - accuracy: 0.8986
Epoch 6/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2626 - accuracy: 0.9022
Epoch 7/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2504 - accuracy: 0.9055
Epoch 8/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2420 - accuracy: 0.9105
Epoch 9/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2287 - accuracy: 0.9153
Epoch 10/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.217

In [16]:
model_fashion.evaluate(x_test_fashion, y_test_fashion)

313/313 [==============================] - 1s 2ms/step - loss: 0.3717 - accuracy: 0.8907


[0.37171122431755066, 0.8906999826431274]

# **HANDWRITING MNIST - NUMBERS 0 TO 9**

In [17]:
import tensorflow as tf

hw_mnist = tf.keras.datasets.mnist

(x_train_hw, y_train_hw), (x_test_hw, y_test_hw) = hw_mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [18]:
import numpy as np
np.set_printoptions(linewidth=200)

In [19]:
print(x_train_hw[29])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   3  37  37  3

In [20]:
y_train_hw[29]

7

In [21]:
x_train_hw.shape, x_test_hw.shape, y_train_hw.shape, y_test_hw.shape

((60000, 28, 28), (10000, 28, 28), (60000,), (10000,))

In [22]:
len(np.unique(y_test_hw))

10

In [28]:
model_hw = tf.keras.models.Sequential([
                                       tf.keras.layers.Flatten(),
                                       tf.keras.layers.Dense(512, activation='relu'),
                                       tf.keras.layers.Dense(10, activation='softmax')
])

In [29]:
model_hw.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [30]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epochs, logs={}):
    if(logs.get('accuracy')>=0.99):
      print('Reached 99% accuracy so cancelling training!')
      self.model.stop_training = True

callbacks = myCallback()

In [31]:
model_hw.fit(x_train_hw, y_train_hw, epochs=20, callbacks=[callbacks])

Epoch 1/20
1875/1875 [==============================] - 9s 4ms/step - loss: 7.2085 - accuracy: 0.8688
Epoch 2/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3234 - accuracy: 0.9381
Epoch 3/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3171 - accuracy: 0.9412
Epoch 4/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2735 - accuracy: 0.9446
Epoch 5/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2381 - accuracy: 0.9501
Epoch 6/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2073 - accuracy: 0.9549
Epoch 7/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2114 - accuracy: 0.9555
Epoch 8/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1964 - accuracy: 0.9589
Epoch 9/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1862 - accuracy: 0.9610
Epoch 10/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.179

In [32]:
model_hw.evaluate(x_test_hw, y_test_hw)

313/313 [==============================] - 1s 2ms/step - loss: 0.5044 - accuracy: 0.9597


[0.5043660402297974, 0.9596999883651733]

In [33]:
preds = model_hw.predict(x_test_hw)

In [34]:
preds_3 = model_hw.predict(x_test_hw[:3])
preds_3

array([[0.0000000e+00, 3.6192018e-18, 9.8551841e-24, 2.5878072e-20, 6.1025013e-34, 4.7327932e-31, 0.0000000e+00, 1.0000000e+00, 4.2296177e-31, 4.8026259e-18],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 8.5009258e-37, 2.1389802e-32, 7.1737513e-37, 0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [35]:
y_test_hw[:3]

array([7, 2, 1], dtype=uint8)